# Generated by Django 6.1.2 on 2026-10-09 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_tripstop'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('idea', 'Idea'), ('selected', 'Selected'), ('rejected', 'Rejected')], default='idea', max_length=20)),
                ('url', models.URLField(blank=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to='trips.trip')),
            ],
        ),
        migrations.CreateModel(
            name='TripIdeaVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_user_id', models.PositiveBigIntegerField()),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='trips.tripidea')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('idea', 'discord_user_id'), name='unique_trip_idea_vote')],
            },
        ),
    ]
