# Generated by Django 6.1.2 on 2026-10-09 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_tripidea_tripideavote'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_items', to='trips.trip')),
                ('trip_idea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_items', to='trips.tripidea')),
                ('trip_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_items', to='trips.tripstop')),
            ],
        ),
    ]
