# Generated by Django 6.1.2 on 2026-10-09 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_planitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='planitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='planitem',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitem',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='planitem',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='tripidea',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tripidea',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('is_done', models.BooleanField(default=False)),
                ('assigned_to', models.PositiveBigIntegerField(blank=True, null=True)),
                ('plan_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='trips.planitem')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='trips.trip')),
            ],
        ),
    ]
