# Generated by Django 6.1.2 on 2026-10-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_planitem_description_planitem_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripstop',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
