# Generated by Django 6.1.2 on 2026-10-09 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_tripstop_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_user_id', models.PositiveBigIntegerField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='trips.trip')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('trip', 'discord_user_id'), name='unique_trip_member')],
            },
        ),
    ]
