# Generated by Django 6.1.2 on 2026-10-09 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_tripmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('cost_type', models.CharField(choices=[('total', 'Total'), ('per_person', 'Per person')], max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('plan_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_items', to='trips.planitem')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_items', to='trips.trip')),
            ],
        ),
    ]
